### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by takano-hi** [midwhite/quiz-master-app#1]
## Set up
- [x] init project as Vue.js
- [x] enable to use vue-router
- [x] enable to use vuex
- [x] set up unit tests
- [x] enable to use i18n

### application layer
- [x] enable to access API with Authentication header
- [ ] enable to handle errors (API access)
- [x] enable to handle errors (component)
- [x] enable to sign up
- [x] enable to sign in
- [x] enable to sign out
- [x] create StorageService
- [ ] transition animation when router change

### shared components
- [x] create welcome page
- [x] enable to show flash messages with snackbar
- [ ] enable to show is-loading
- [x] create header component
- [x] create footer component
- [x] enable to switch locale

### quiz CRUD component
- [x] enable to create quizzes
- [x] enable to update quizzes
- [x] enable to list quizzes
- [x] enable to delete quizzes
- [x] paging quizzes

### quiz-mode
- [x] enable to list quizzes on quiz-mode
- [x] enable to send answer
- [x] enable to check correctness and explanation

## check before release
- [x] write README.md
- [x] pass all the tests
- [x] check XSS prevention
- [ ] OGP meta tags
- [ ] introduce Google Analytics
- [ ] refactoring action-types
